const FMS = [
   {
      id: 1,
      imgAddress: '/images/FMS/squatting.png',
      title: 'اسکات کامل',
      imgSize: 'sm',
      keys: [0, 1, 2, 3],
      values: [0, 1, 2, 3],
   },
   {
      id: 2,
      imgAddress: '/images/FMS/stepping.png',
      title: 'عبور از مانع راست',
      imgSize: 'sm',
      keys: [0, 1, 2, 3],
      values: [0, 1, 2, 3],
   },
   {
      id: 3,
      imgAddress: '/images/FMS/stepping.png',
      title: 'عبور از مانع چپ',
      imgSize: 'sm',
      keys: [0, 1, 2, 3],
      values: [0, 1, 2, 3],
   },
   {
      id: 4,
      imgAddress: '/images/FMS/lunging.png',
      title: 'لانچ خطی راست',
      imgSize: 'sm',
      keys: [0, 1, 2, 3],
      values: [0, 1, 2, 3],
   },
   {
      id: 5,
      imgAddress: '/images/FMS/lunging.png',
      title: 'لانچ خطی چپ',
      imgSize: 'sm',
      keys: [0, 1, 2, 3],
      values: [0, 1, 2, 3],
   },
   {
      id: 6,
      imgAddress: '/images/FMS/reaching.png',
      title: 'تحرک پذیری شانه ها راست',
      imgSize: 'sm',
      keys: [0, 1, 2, 3],
      values: [0, 1, 2, 3],
   },
   {
      id: 7,
      imgAddress: '/images/FMS/reaching.png',
      title: 'تحرک پذیری شانه ها چپ',
      imgSize: 'sm',
      keys: [0, 1, 2, 3],
      values: [0, 1, 2, 3],
   },
   {
      id: 8,
      imgAddress: '/images/FMS/leg-raising.png',
      title: 'بالا آوردن فعال پا راست',
      imgSize: 'lg',
      keys: [0, 1, 2, 3],
      values: [0, 1, 2, 3],
   },
   {
      id: 9,
      imgAddress: '/images/FMS/leg-raising.png',
      title: 'بالا آوردن فعال پا چپ',
      imgSize: 'lg',
      keys: [0, 1, 2, 3],
      values: [0, 1, 2, 3],
   },
   {
      id: 10,
      imgAddress: '/images/FMS/push-up.png',
      title: 'شنای سوئدی',
      imgSize: 'lg',
      keys: [0, 1, 2, 3],
      values: [0, 1, 2, 3],
   },
   {
      id: 11,
      imgAddress: '/images/FMS/rotary-stability.png',
      title: 'ثبات چرخشی راست',
      imgSize: 'lg',
      keys: [0, 1, 2, 3],
      values: [0, 1, 2, 3],
   },
   {
      id: 12,
      imgAddress: '/images/FMS/rotary-stability.png',
      title: 'ثبات چرخشی چپ',
      imgSize: 'lg',
      keys: [0, 1, 2, 3],
      values: [0, 1, 2, 3],
   },
]

export default FMS;